### ISSUE TITLE
A PROBLEM

### ISSUE THREAD

**Issue by TianZonglin** [Didericis/github-contributions-api#1]
> Currently hosted on heroku: https://github-contributions-api.herokuapp.com

Hi, today I called this api and got an `Access-Control-Allow-Origin` error, could you please add the support of `Access-Control-Allow-Origin: *` for our users to use it.

**Comment by Didericis** [comment]
This was an educational exercise that wasn't really intended for production use. I'll add a disclaimer to the README.

The api is different, but someone sort of cloned this project and seems to be using it in production: https://github.com/sallar/github-contributions-api
